# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Spencer
email: rob@robspencer.me.uk
description: > # this means to ignore newlines until "baseurl:"
  My name is Robert Spencer. I am a Software Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.robspencer.me.uk" # the base hostname & protocol for your site
twitter_username: rjspencer1989
github_username:  rjspencer1989
linkedin_username: robert-spencer-6b096511b

# Build settings
exclude: ["package.json", "Gruntfile.js"]
plugins: []
markdown: kramdown
sass:
  load_paths:
    - _sass
    - node_modules

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
